//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD_3200_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lesson
    {
        public int lesson_ID { get; set; }
        public Nullable<int> course_ID { get; set; }
        public string lesson_name { get; set; }
        public string lesson_desc { get; set; }
        public string lesson_link { get; set; }
    
        public virtual cours cours { get; set; }
    }
}
