//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD_3200_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class elearningEntities : DbContext
    {
        public elearningEntities()
            : base("name=elearningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attempt> attempts { get; set; }
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<enroll> enrolls { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<instructor> instructors { get; set; }
        public virtual DbSet<lesson> lessons { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<quiz> quizs { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<answer> answers { get; set; }
    }
}
